HOSTS:
  # postgres:
  #   roles:
  #      - db
  #   platform: debian-7-x64
  #   image: postgres:8.4.22
  #   hypervisor: docker
  #   docker_cmd: ["/bin/bash", "-c", "/usr/sbin/sshd -D -o 'PermitRootLogin yes' -o 'PasswordAuthentication yes' & /docker-entrypoint.sh postgres"]
  tomcat:
    roles:
      - default
      - webapp
    platform: ubuntu-14.04-x64
    image: csanchez/appfuse-tomcat
    hypervisor: docker
    docker_cmd: ["/bin/bash", "-c", "/usr/sbin/sshd -D -o 'PermitRootLogin yes' -o 'PasswordAuthentication yes' & /run.sh"]
CONFIG:
  log_level: debug
  type: git
